import React from "react";

function Policy() {
  return (
    <main className="policyPage">
      <div className="policyPage_container">
        <div className="content policyPage__title_content">
          <div className="policyPage-title ">1. Introduction</div>
        </div>
        <div className="policyPage__text_content">
          <span>
            Our Privacy Policy governs your visit to
            https://reviewforport.onrender.com, and explains how we collect,
            safeguard and disclose information that results from your use of our
            Service. We use your data to provide and improve Service. By using
            Service, you agree to the collection and use of information in
            accordance with this policy. Unless otherwise defined in this
            Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms and Conditions. Our Terms and Conditions
            ("Terms") govern all use of our Service and together with the
            Privacy Policy constitutes your agreement with us ("agreement").
          </span>
        </div>
        <div className="content policyPage__title_content">
          <div className="policyPage-title">2. Definitions</div>
        </div>
        <div className="policyPage__text_content">
          <span>
            SERVICE means the https://reviewforport.onrender.com website{" "}
            <br></br>
            <br></br>
            <br></br>
            PERSONAL DATA means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
            <br></br>
            <br></br>
            <br></br>
            USAGE DATA is data collected automatically either generated by the
            use of <br></br>
            <br></br>
            <br></br>Service or from Service infrastructure itself (for example,
            the duration of a page visit).<br></br>
            <br></br>
            <br></br> COOKIES are small files stored on your device (computer or
            mobile device).<br></br>
            <br></br>
            <br></br> DATA CONTROLLER means a natural or legal person who
            (either alone or jointly or in common with other persons) determines
            the purposes for which and the manner in which any personal data
            are, or are to be, processed. For the purpose of this Privacy
            Policy, we are a Data Controller of your data.<br></br>
            <br></br>
            <br></br> DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural
            or legal person who processes the data on behalf of the Data
            Controller. We may use the services of various Service Providers in
            order to process your data more effectively.<br></br>
            <br></br>
            <br></br> DATA SUBJECT is any living individual who is the subject
            of Personal Data.<br></br>
            <br></br>
            <br></br> THE USER is the individual using our Service. The User
            corresponds to the Data Subject, who is the subject of Personal
            Data.
          </span>
        </div>
        <div className="content policyPage__title_content">
          <div className="policyPage-title">3. Types of Data Collected</div>
        </div>
        <div className="policyPage__text_content">
          <span>
            Personal Data While using our Service, we may ask you to provide us
            with certain personally identifiable information that can be used to
            contact or identify you ("Personal Data"). Personally identifiable
            information includes:<br></br>
            <br></br>• First name and last name <br></br>
            <br></br>• Email address<br></br>
            <br></br>• Language settings<br></br>
            <br></br>• Profile picture<br></br>
            <br></br>
          </span>
        </div>
        <div className="content policyPage__title_content">
          <div className="policyPage-title">4. Use of Data</div>
        </div>
        <div className="policyPage__text_content">
          <span>
            We use the collected data for various purposes: <br></br>
            <br></br>• to provide and maintain our Service <br></br>
            <br></br>• to provide review functionality in our Service (rendering
            personal information above review text to let other people identify
            you. Also it allows the code of our Service to understand if you
            have already liked any reviews to provide one user - one like
            functionality. Also reporting reviews needs personal data to
            identify) <br></br>
            <br></br>• to allow you to participate in interactive features of
            our Service when you choose to do so<br></br>
            <br></br>• to provide customer support<br></br>
            <br></br>• to gather analysis or valuable information so that we can
            improve our Service<br></br>
            <br></br>• to fulfill any other purpose for which you provide it
            <br></br>
            <br></br>
          </span>
        </div>
        <div className="content policyPage__title_content">
          <div className="policyPage-title">5. Retention of Data</div>
        </div>
        <div className="policyPage__text_content">
          <span>
            We will retain your Personal Data only for as long as is necessary
            for the purposes set out in this Privacy Policy. We will retain and
            use your Personal Data to the extent necessary to comply with our
            legal obligations (for example, if we are required to retain your
            data to comply with applicable laws), resolve disputes, and enforce
            our legal agreements and policies.
          </span>
        </div>
        <div className="content policyPage__title_content">
          <div className="policyPage-title">6. Transfer of Data</div>
        </div>
        <div className="policyPage__text_content">
          <span>
            Your information, including Personal Data, may be transferred to -
            and maintained on - computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction. Your
            consent to this Privacy Policy followed by your submission of such
            information represents your agreement to that transfer.
          </span>
        </div>
      </div>
    </main>
  );
}

export default Policy;
